// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExample = "example"

// Example mapped from table <example>
type Example struct {
	Example string `gorm:"column:example;not null;default:'^\S+$'" json:"example"`
}

// TableName Example's table name
func (*Example) TableName() string {
	return TableNameExample
}
