version: '3.9'

services:
  mysql:
    image: 'mariadb:latest'
    ports:
      - 9910:3306
    networks:
      - test
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    volumes:
      - .:/etc/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--defaults-file=/etc/mysql/mariadb.config", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
  app:
    build:
      context: .
    networks:
      - test
    volumes:
      - .:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
networks:
  test:
    driver: bridge
