// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gorm.io/playground/model"
)

func newPet(db *gorm.DB, opts ...gen.DOOption) pet {
	_pet := pet{}

	_pet.petDo.UseDB(db, opts...)
	_pet.petDo.UseModel(&model.Pet{})

	tableName := _pet.petDo.TableName()
	_pet.ALL = field.NewAsterisk(tableName)
	_pet.ID = field.NewUint(tableName, "id")
	_pet.CreatedAt = field.NewTime(tableName, "created_at")
	_pet.UpdatedAt = field.NewTime(tableName, "updated_at")
	_pet.DeletedAt = field.NewField(tableName, "deleted_at")
	_pet.UserID = field.NewUint(tableName, "user_id")
	_pet.Name = field.NewString(tableName, "name")
	_pet.Toy = petHasOneToy{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Toy", "model.Toy"),
	}

	_pet.fillFieldMap()

	return _pet
}

type pet struct {
	petDo petDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	UserID    field.Uint
	Name      field.String
	Toy       petHasOneToy

	fieldMap map[string]field.Expr
}

func (p pet) Table(newTableName string) *pet {
	p.petDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pet) As(alias string) *pet {
	p.petDo.DO = *(p.petDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pet) updateTableName(table string) *pet {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.UserID = field.NewUint(table, "user_id")
	p.Name = field.NewString(table, "name")

	p.fillFieldMap()

	return p
}

func (p *pet) WithContext(ctx context.Context) *petDo { return p.petDo.WithContext(ctx) }

func (p pet) TableName() string { return p.petDo.TableName() }

func (p pet) Alias() string { return p.petDo.Alias() }

func (p pet) Columns(cols ...field.Expr) gen.Columns { return p.petDo.Columns(cols...) }

func (p *pet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pet) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["name"] = p.Name

}

func (p pet) clone(db *gorm.DB) pet {
	p.petDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pet) replaceDB(db *gorm.DB) pet {
	p.petDo.ReplaceDB(db)
	return p
}

type petHasOneToy struct {
	db *gorm.DB

	field.RelationField
}

func (a petHasOneToy) Where(conds ...field.Expr) *petHasOneToy {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a petHasOneToy) WithContext(ctx context.Context) *petHasOneToy {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a petHasOneToy) Session(session *gorm.Session) *petHasOneToy {
	a.db = a.db.Session(session)
	return &a
}

func (a petHasOneToy) Model(m *model.Pet) *petHasOneToyTx {
	return &petHasOneToyTx{a.db.Model(m).Association(a.Name())}
}

type petHasOneToyTx struct{ tx *gorm.Association }

func (a petHasOneToyTx) Find() (result *model.Toy, err error) {
	return result, a.tx.Find(&result)
}

func (a petHasOneToyTx) Append(values ...*model.Toy) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a petHasOneToyTx) Replace(values ...*model.Toy) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a petHasOneToyTx) Delete(values ...*model.Toy) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a petHasOneToyTx) Clear() error {
	return a.tx.Clear()
}

func (a petHasOneToyTx) Count() int64 {
	return a.tx.Count()
}

type petDo struct{ gen.DO }

func (p petDo) Debug() *petDo {
	return p.withDO(p.DO.Debug())
}

func (p petDo) WithContext(ctx context.Context) *petDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p petDo) ReadDB() *petDo {
	return p.Clauses(dbresolver.Read)
}

func (p petDo) WriteDB() *petDo {
	return p.Clauses(dbresolver.Write)
}

func (p petDo) Session(config *gorm.Session) *petDo {
	return p.withDO(p.DO.Session(config))
}

func (p petDo) Clauses(conds ...clause.Expression) *petDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p petDo) Returning(value interface{}, columns ...string) *petDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p petDo) Not(conds ...gen.Condition) *petDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p petDo) Or(conds ...gen.Condition) *petDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p petDo) Select(conds ...field.Expr) *petDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p petDo) Where(conds ...gen.Condition) *petDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p petDo) Order(conds ...field.Expr) *petDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p petDo) Distinct(cols ...field.Expr) *petDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p petDo) Omit(cols ...field.Expr) *petDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p petDo) Join(table schema.Tabler, on ...field.Expr) *petDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p petDo) LeftJoin(table schema.Tabler, on ...field.Expr) *petDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p petDo) RightJoin(table schema.Tabler, on ...field.Expr) *petDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p petDo) Group(cols ...field.Expr) *petDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p petDo) Having(conds ...gen.Condition) *petDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p petDo) Limit(limit int) *petDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p petDo) Offset(offset int) *petDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p petDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *petDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p petDo) Unscoped() *petDo {
	return p.withDO(p.DO.Unscoped())
}

func (p petDo) Create(values ...*model.Pet) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p petDo) CreateInBatches(values []*model.Pet, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p petDo) Save(values ...*model.Pet) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p petDo) First() (*model.Pet, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pet), nil
	}
}

func (p petDo) Take() (*model.Pet, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pet), nil
	}
}

func (p petDo) Last() (*model.Pet, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pet), nil
	}
}

func (p petDo) Find() ([]*model.Pet, error) {
	result, err := p.DO.Find()
	return result.([]*model.Pet), err
}

func (p petDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Pet, err error) {
	buf := make([]*model.Pet, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p petDo) FindInBatches(result *[]*model.Pet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p petDo) Attrs(attrs ...field.AssignExpr) *petDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p petDo) Assign(attrs ...field.AssignExpr) *petDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p petDo) Joins(fields ...field.RelationField) *petDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p petDo) Preload(fields ...field.RelationField) *petDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p petDo) FirstOrInit() (*model.Pet, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pet), nil
	}
}

func (p petDo) FirstOrCreate() (*model.Pet, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Pet), nil
	}
}

func (p petDo) FindByPage(offset int, limit int) (result []*model.Pet, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p petDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p petDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p petDo) Delete(models ...*model.Pet) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *petDo) withDO(do gen.Dao) *petDo {
	p.DO = *do.(*gen.DO)
	return p
}
