// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"playground/model"
)

func newUser(db *gorm.DB, opts ...gen.DOOption) user {
	_user := user{}

	_user.userDo.UseDB(db, opts...)
	_user.userDo.UseModel(&model.User{})

	tableName := _user.userDo.TableName()
	_user.ALL = field.NewAsterisk(tableName)
	_user.ID = field.NewUint(tableName, "id")
	_user.CreatedAt = field.NewTime(tableName, "created_at")
	_user.UpdatedAt = field.NewTime(tableName, "updated_at")
	_user.DeletedAt = field.NewField(tableName, "deleted_at")
	_user.UserMainID = field.NewUint(tableName, "user_main_id")
	_user.Username = field.NewString(tableName, "username")
	_user.UserExtInfo = userHasOneUserExtInfo{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("UserExtInfo", "model.UserExt"),
		UserInfo: struct {
			field.RelationField
			UserExtInfo struct {
				field.RelationField
			}
			UserAccountRelationInfo struct {
				field.RelationField
				UserInfo struct {
					field.RelationField
				}
				AccountInfo struct {
					field.RelationField
					CompanyInfo struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("UserExtInfo.UserInfo", "model.User"),
			UserExtInfo: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("UserExtInfo.UserInfo.UserExtInfo", "model.UserExt"),
			},
			UserAccountRelationInfo: struct {
				field.RelationField
				UserInfo struct {
					field.RelationField
				}
				AccountInfo struct {
					field.RelationField
					CompanyInfo struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("UserExtInfo.UserInfo.UserAccountRelationInfo", "model.UserAccountRelation"),
				UserInfo: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("UserExtInfo.UserInfo.UserAccountRelationInfo.UserInfo", "model.User"),
				},
				AccountInfo: struct {
					field.RelationField
					CompanyInfo struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("UserExtInfo.UserInfo.UserAccountRelationInfo.AccountInfo", "model.Account"),
					CompanyInfo: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("UserExtInfo.UserInfo.UserAccountRelationInfo.AccountInfo.CompanyInfo", "model.Company"),
					},
				},
			},
		},
	}

	_user.UserAccountRelationInfo = userHasOneUserAccountRelationInfo{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("UserAccountRelationInfo", "model.UserAccountRelation"),
	}

	_user.fillFieldMap()

	return _user
}

type user struct {
	userDo userDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	UserMainID  field.Uint
	Username    field.String
	UserExtInfo userHasOneUserExtInfo

	UserAccountRelationInfo userHasOneUserAccountRelationInfo

	fieldMap map[string]field.Expr
}

func (u user) Table(newTableName string) *user {
	u.userDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user) As(alias string) *user {
	u.userDo.DO = *(u.userDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user) updateTableName(table string) *user {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")
	u.UserMainID = field.NewUint(table, "user_main_id")
	u.Username = field.NewString(table, "username")

	u.fillFieldMap()

	return u
}

func (u *user) WithContext(ctx context.Context) *userDo { return u.userDo.WithContext(ctx) }

func (u user) TableName() string { return u.userDo.TableName() }

func (u user) Alias() string { return u.userDo.Alias() }

func (u user) Columns(cols ...field.Expr) gen.Columns { return u.userDo.Columns(cols...) }

func (u *user) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
	u.fieldMap["user_main_id"] = u.UserMainID
	u.fieldMap["username"] = u.Username

}

func (u user) clone(db *gorm.DB) user {
	u.userDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u user) replaceDB(db *gorm.DB) user {
	u.userDo.ReplaceDB(db)
	return u
}

type userHasOneUserExtInfo struct {
	db *gorm.DB

	field.RelationField

	UserInfo struct {
		field.RelationField
		UserExtInfo struct {
			field.RelationField
		}
		UserAccountRelationInfo struct {
			field.RelationField
			UserInfo struct {
				field.RelationField
			}
			AccountInfo struct {
				field.RelationField
				CompanyInfo struct {
					field.RelationField
				}
			}
		}
	}
}

func (a userHasOneUserExtInfo) Where(conds ...field.Expr) *userHasOneUserExtInfo {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasOneUserExtInfo) WithContext(ctx context.Context) *userHasOneUserExtInfo {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasOneUserExtInfo) Session(session *gorm.Session) *userHasOneUserExtInfo {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasOneUserExtInfo) Model(m *model.User) *userHasOneUserExtInfoTx {
	return &userHasOneUserExtInfoTx{a.db.Model(m).Association(a.Name())}
}

type userHasOneUserExtInfoTx struct{ tx *gorm.Association }

func (a userHasOneUserExtInfoTx) Find() (result *model.UserExt, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasOneUserExtInfoTx) Append(values ...*model.UserExt) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasOneUserExtInfoTx) Replace(values ...*model.UserExt) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasOneUserExtInfoTx) Delete(values ...*model.UserExt) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasOneUserExtInfoTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasOneUserExtInfoTx) Count() int64 {
	return a.tx.Count()
}

type userHasOneUserAccountRelationInfo struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasOneUserAccountRelationInfo) Where(conds ...field.Expr) *userHasOneUserAccountRelationInfo {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasOneUserAccountRelationInfo) WithContext(ctx context.Context) *userHasOneUserAccountRelationInfo {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasOneUserAccountRelationInfo) Session(session *gorm.Session) *userHasOneUserAccountRelationInfo {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasOneUserAccountRelationInfo) Model(m *model.User) *userHasOneUserAccountRelationInfoTx {
	return &userHasOneUserAccountRelationInfoTx{a.db.Model(m).Association(a.Name())}
}

type userHasOneUserAccountRelationInfoTx struct{ tx *gorm.Association }

func (a userHasOneUserAccountRelationInfoTx) Find() (result *model.UserAccountRelation, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasOneUserAccountRelationInfoTx) Append(values ...*model.UserAccountRelation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasOneUserAccountRelationInfoTx) Replace(values ...*model.UserAccountRelation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasOneUserAccountRelationInfoTx) Delete(values ...*model.UserAccountRelation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasOneUserAccountRelationInfoTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasOneUserAccountRelationInfoTx) Count() int64 {
	return a.tx.Count()
}

type userDo struct{ gen.DO }

func (u userDo) Debug() *userDo {
	return u.withDO(u.DO.Debug())
}

func (u userDo) WithContext(ctx context.Context) *userDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDo) ReadDB() *userDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDo) WriteDB() *userDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDo) Session(config *gorm.Session) *userDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDo) Clauses(conds ...clause.Expression) *userDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDo) Returning(value interface{}, columns ...string) *userDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDo) Not(conds ...gen.Condition) *userDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDo) Or(conds ...gen.Condition) *userDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDo) Select(conds ...field.Expr) *userDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDo) Where(conds ...gen.Condition) *userDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDo) Order(conds ...field.Expr) *userDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDo) Distinct(cols ...field.Expr) *userDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDo) Omit(cols ...field.Expr) *userDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDo) Join(table schema.Tabler, on ...field.Expr) *userDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDo) RightJoin(table schema.Tabler, on ...field.Expr) *userDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDo) Group(cols ...field.Expr) *userDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDo) Having(conds ...gen.Condition) *userDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDo) Limit(limit int) *userDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDo) Offset(offset int) *userDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDo) Unscoped() *userDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDo) Create(values ...*model.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDo) CreateInBatches(values []*model.User, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDo) Save(values ...*model.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDo) First() (*model.User, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) Take() (*model.User, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) Last() (*model.User, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) Find() ([]*model.User, error) {
	result, err := u.DO.Find()
	return result.([]*model.User), err
}

func (u userDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User, err error) {
	buf := make([]*model.User, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDo) FindInBatches(result *[]*model.User, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDo) Attrs(attrs ...field.AssignExpr) *userDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDo) Assign(attrs ...field.AssignExpr) *userDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDo) Joins(fields ...field.RelationField) *userDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDo) Preload(fields ...field.RelationField) *userDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDo) FirstOrInit() (*model.User, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) FirstOrCreate() (*model.User, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) FindByPage(offset int, limit int) (result []*model.User, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDo) Delete(models ...*model.User) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDo) withDO(do gen.Dao) *userDo {
	u.DO = *do.(*gen.DO)
	return u
}
