// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int32          `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name      string         `gorm:"column:name" json:"name"`
	Age       int32          `gorm:"column:age" json:"age"`
	Birthday  time.Time      `gorm:"column:birthday" json:"birthday"`
	CompanyID int32          `gorm:"column:company_id" json:"company_id"`
	ManagerID int32          `gorm:"column:manager_id" json:"manager_id"`
	Active    int32          `gorm:"column:active" json:"active"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
